### ISSUE TITLE
Error: Unknown archive format

### ISSUE THREAD

**Issue by eszlari** [flatpak/flatpak-builder#158]
It seems `type: archive` has problems with archives without a file extension:

```yaml
    sources:
      - type: archive
        url: https://dl.pstmn.io/download/version/6.1.3/linux64
        sha256: 6e08dae1524416396921337dd785e84436c1887a7d835b24c69ea68dce13290d
```

```
Error: module Postman: Unknown archive format of '.flatpak-builder/downloads/6e08dae1524416396921337dd785e84436c1887a7d835b24c69ea68dce13290d/linux64'
```
