### ISSUE TITLE
Unnecessary rebuilds for modules containing a + in their name

### ISSUE THREAD

**Issue by kirbyfan64** [flatpak/flatpak-builder#214]
Example YAML file:

```yaml
app-id: com.test.Test
runtime: org.freedesktop.Platform
runtime-version: 18.08
sdk: org.freedesktop.Sdk
modules:
  - name: libxpp
    buildsystem: simple
    build-commands:
      - 'echo "Build libxpp"'
  - name: libx++
    buildsystem: simple
    build-commands:
      - 'echo "Build libx++"'
  - name: test
    buildsystem: simple
    build-commands:
      - 'echo "Build test"'
```

- When you run `flatpak-builder` the first time, it (of course) runs a full build.
- Run it again, and it reuses the cache.
- Run it again, and it rebuilds `libx++`.
- Run it again, and it reuses the cache.
- Run it again, and it rebuilds `libx++`
- Run it again, and it reuses the cache.
- ...

Basically, every other build results in rebuilding libx++.
