### ISSUE TITLE
builder not extracting tar.gz

### ISSUE THREAD

**Issue by hbons** [flatpak/flatpak-builder#222]
I'm running into this weird issue with flatpak `1.0.3`. flatpak-builder errors out when building a module of the `archive` type with the `simple` build system.

```
Cache hit for openssh, skipping build
Cache hit for git, skipping build
Cache miss, checking out last cache hit
========================================================================
Building module git-lfs in /home/hbons/Projects/org.sparkleshare.SparkleShare/.flatpak-builder/build/git-lfs-6
========================================================================
Running: pwd
/run/build/git-lfs
Running: ls
Running: cp git-lfs /app/libexec/git-core/
cp: cannot stat 'git-lfs': No such file or directory
Error: module git-lfs: Child process exited with code 1
```

Here's the relevant part of the spec:
```
    - name: git-lfs
      sources:
          - type: archive
            url: 'https://github.com/git-lfs/git-lfs/releases/download/v2.5.1/git-lfs-linux-amd64-v2.5.1.tar.gz'
            sha256: 9565fa9c2442c3982567a3498c9352cda88e0f6a982648054de0440e273749e7
      buildsystem: simple
      build-commands:
          - pwd
          - ls
          - cp git-lfs /app/libexec/git-core/
```

I've added the `pwd` and `ls` commands for debugging. As you can see shows that the source folder is empty.  flatpak-builder downloads the file just fine. I think something went wrong with the extraction? I can extract the files manually fine and can see the required files.
