### ISSUE TITLE
Add extension option to the archive source type

### ISSUE THREAD

**Issue by roipoussiere** [flatpak/flatpak-builder#301]
I'm not able to download this archive: `https://github.com/tpaviot/oce/tarball/master`, because the archive format is not recognized.

Could it be possible to add the `extension` option in the archive source type?

I means something like:

```yaml
    sources:
      - type: archive
        url: https://github.com/tpaviot/oce/tarball/master
        sha256: 04966cedb9beb56dd84de187ec9d27ff66cb13a6c14e3a1f9bf41563c38550f7
        extension: tar.gz
```

Related: #25
