### ISSUE TITLE
how to edit files that are not sources?

### ISSUE THREAD

**Issue by roipoussiere** [flatpak/flatpak-builder#345]
I'm trying to build [Open Cascade](https://www.opencascade.com/doc/occt-7.2.0/overview/html/occt_dev_guides__building.html) and I'm facing the error `missing file xlocale.h`. After some search I found that [a solution](https://github.com/agracio/electron-edge-js/issues/16#issuecomment-385620483) was to create a symlink: `ln -s /usr/include/locale.h /usr/include/xlocale.h`

But how to do this from the flatpak context?

I tried this:
```yml
  - name: occt
    sources:
      - type: archive
        url: https://github.com/tpaviot/oce/releases/download/official-upstream-packages/opencascade-7.2.0.tgz
        md5: 5fcdd7a9bcb797ced2e4c00f59b3f5aa
      - type: shell
        commands:
          - ln -s /usr/include/locale.h /usr/include/xlocale.h
    buildsystem: cmake
    config-opts:
      - -DOCE_INSTALL_PREFIX:PATH=/app
```

But it seems (obviously) that `sources.commands` is not supposed to edit non-sources files:

```
Building module occt in /home/nath/divers/flat_cadquery/.flatpak-builder/build/occt-1
========================================================================
ln: failed to create symbolic link '/usr/include/xlocale.h': Read-only file system
Error: module occt: Child process exited with code 1
```

What should I do?
