### ISSUE TITLE
Cache not used for 'dir' and 'git' sources

### ISSUE THREAD

**Issue by sophie-h** [flatpak/flatpak-builder#356]
## Linux distribution and version

Debian 10

## Flatpak-builder version

1.0.10

## Flatpak version

1.2.5

## Description of the problem

Source of type `dir` and (local?) `git` always lead to "Cache miss"

## Steps to reproduce

```yaml
app-id: org.example.App
runtime: org.gnome.Platform
sdk: org.gnome.Sdk

modules:
  - name: file
    buildsystem: simple
    build-commands: [ echo file ]
    sources:
      - type: file
        path: /etc/os-release
  - name: dir
    buildsystem: simple
    build-commands: [ echo dir ]
    sources:
      - type: dir
        path: ./
  - name: git
    buildsystem: simple
    build-commands: [ echo git ]
    sources:
      - type: git
        path: ./
```

result of second run

```
Cache hit for file, skipping build
Cache miss, checking out last cache hit
========================================================================
Building module dir in /tmp/test/.flatpak-builder/build/dir-1
========================================================================
Running: echo dir
dir
Committing stage build-dir to cache
========================================================================
Building module git in /tmp/test/.flatpak-builder/build/git-1
========================================================================
Already on 'master'
Running: echo git
git
Committing stage build-git to cache
```
