### ISSUE TITLE
patch source: allow patches to be fetched from internet/URL

### ISSUE THREAD

**Issue by dgcampea** [flatpak/flatpak-builder#361]
## Flatpak-builder version
flatpak-builder 1.0.10

## Description of the problem
Feature Request: allow patches/.diff files to be fetched via internet.

**Comment by rderooy** [comment]
This could use some more context, but I think what is being asked for is to support something like the following in the manifest:

```yaml
sources:
  - type: patch
  - url: https://patch-diff.githubusercontent.com/raw/joncampbell123/dosbox-x/pull/3447.diff
  - sha256: f3c2f4284b0be7142e1fbc7ae97fe9c235a101c2dc62c86c17995813f3e47fb3
```
This way you don't need to add patch files to the flatpak repo.
