### ISSUE TITLE
QMake cannot find built libraries

### ISSUE THREAD

**Issue by ttddee** [flatpak/flatpak-builder#370]
## Linux distribution and version

5.9.10-arch1-1

## Flatpak-builder version

flatpak-builder 1.0.11

## Flatpak version

Flatpak 1.8.3

## Description of the problem

When trying to build https://github.com/ttddee/Cascade with qmake the dependencies build fine but then qmake cannot find the built libraries on the last build step.

Error:

```bash
/usr/lib/gcc/x86_64-unknown-linux-gnu/10.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: cannot find -lOpenImageIO
/usr/lib/gcc/x86_64-unknown-linux-gnu/10.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: cannot find -lOpenColorIO
/usr/lib/gcc/x86_64-unknown-linux-gnu/10.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: cannot find -lqtadvanceddocking
/usr/lib/gcc/x86_64-unknown-linux-gnu/10.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: cannot find -lgmic
/usr/lib/gcc/x86_64-unknown-linux-gnu/10.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: cannot find -ltbb
collect2: error: ld returned 1 exit status
make: *** [Makefile:585: Cascade] Error 1
Error: module Cascade: Child process exited with code 2
```

The manifest:

```yaml
app-id: org.ttddee.Cascade
runtime: org.kde.Platform
runtime-version: '5.15'
sdk: org.kde.Sdk
command: Cascade
finish-args:
  - --share=ipc
  - --socket=x11
  - --socket=wayland
  - --filesystem=host
  - --device=dri
modules:
  - name: robin-map
    buildsystem: cmake
    builddir: true
    sources: 
      - type: git
        url: https://github.com/Tessil/robin-map.git
        tag: v0.6.3
  - name: fmt
    buildsystem: cmake
    builddir: true
    sources: 
      - type: git
        url: https://github.com/fmtlib/fmt.git
        tag: 7.1.3
  - name: OpenEXR
    buildsystem: cmake
    config-opts: 
      - -DINSTALL_OPENEXR_EXAMPLES=OFF
    builddir: true
    sources: 
      - type: git
        url: https://github.com/AcademySoftwareFoundation/openexr.git
        tag: v2.5.3
  - name: boost
    sources:
      - type: archive
        url: https://downloads.sourceforge.net/project/boost/boost/1.74.0/boost_1_74_0.tar.bz2
        sha256: 83bfc1507731a0906e387fc28b7ef5417d591429e51e788417fe9ff025e116b1
      - type: file
        path: boost-configure
        dest-filename: configure
  - name: Gmic
    buildsystem: cmake-ninja
    config-opts: 
      - -DBUILD_BASH_COMPLETION=OFF
      - -DBUILD_CLI=OFF
      - -DBUILD_MAN=OFF 
    sources: 
      - type: archive
        url: https://gmic.eu/files/source/gmic_2.9.4.tar.gz
        sha256: 790bee48f496765f6b59067dfb10dc34e1eb576caf9a95f30af0d567026eacc7
  - name: TBB
    buildsystem: cmake
    builddir: true
    sources: 
      - type: git
        url: https://github.com/wjakob/tbb.git
        tag: tbb44u4
  - name: OpenColorIO
    buildsystem: cmake
    config-opts: 
      - -DOCIO_WARNING_AS_ERROR=OFF
      - -DOCIO_BUILD_TESTS=OFF
      - -DOCIO_BUILD_APPS=OFF
      - -DOCIO_BUILD_GPU_TESTS=OFF
      - -DOCIO_BUILD_DOCS=OFF
      - -DOCIO_BUILD_PYTHON=OFF
      - -DOCIO_BUILD_TESTS=OFF
    build-options:
      cflags: -Wno-error
      cxxflags: -Wno-error
    builddir: true
    sources: 
      - type: archive
        url: https://github.com/imageworks/OpenColorIO/archive/v1.0.9.tar.gz
        sha256: 27c81e691c15753cd2b560c2ca4bd5679a60c2350eedd43c99d44ca25d65ea7f
  - name: OpenImageIO
    buildsystem: cmake
    config-opts: 
      - -DUSE_PYTHON=0
      - -DUSE_QT=0
      - -DUSE_OPENGL=0
      - -DBUILD_TESTING=0
      - -DBUILD_DOCS=0
    builddir: true
    sources: 
      - type: git
        url: https://github.com/OpenImageIO/oiio.git
        tag: Release-2.2.8.0
  - name: Gtest
    buildsystem: cmake
    sources:
      - type: git
        url: https://github.com/google/googletest.git
        tag: release-1.10.0
  - name: CImg
    buildsystem: simple
    build-commands: 
      - cp CImg.h /app/include
    sources:
      - type: git
        url: https://github.com/dtschump/CImg.git
        tag: v.2.9.4
  - name: Cascade
    buildsystem: qmake
    sources:
      - type: git
        url: https://github.com/ttddee/Cascade
```

How do I tell it the builder where to find the libraries?

## Steps to reproduce

Build above manifest.

**Comment by ttddee** [comment]
The additional `boost-configure` file looks like this in case you want to try and reproduce the issue:

```
./bootstrap.sh "$@"

cat <<EOF >Makefile
all:
        ./b2 -j `nproc`

install:
        ./b2 install
EOF
```

**Comment by eszlari** [comment]
Try:

```
  - name: Cascade
    buildsystem: qmake
    config-opts:
      - LIBS+=-L/app/lib
    sources:
      - type: git
        url: https://github.com/ttddee/Cascade
```

It's always a good idea to use the Github search function on https://github.com/flathub!

See e.g.: https://github.com/flathub/io.github.maurycyliebner.enve/blob/63b3eef66b5308a56578716cf9baace2ac398a4e/io.github.maurycyliebner.enve.yaml#L183
