### ISSUE TITLE
How to build package that required an out-of-source build? cd command does not work.

### ISSUE THREAD

**Issue by kevinsmia1939** [flatpak/flatpak-builder#378]
Operating System: openSUSE Tumbleweed 20210227
KDE Plasma Version: 5.21.0
KDE Frameworks Version: 5.79.0
Qt Version: 5.15.2
Kernel Version: 5.10.16-1-default
OS Type: 64-bit
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-3770 CPU @ 3.40GHz
Memory: 7.5 GiB of RAM
Graphics Processor: Mesa DRI Intel® HD Graphics 4000

flatpak-builder 1.0.11
Flatpak 1.10.1

I have a yaml file like this.
A software called Tomviz. 
https://github.com/OpenChemistry/tomvizsuper

```
app-id: org.tomviz.Tomviz
runtime: org.kde.Platform
sdk: org.kde.Sdk
runtime-version: '5.15'
command: tomviz
finish-args:
  - --share=ipc
  - --socket=x11
  - --socket=wayland
  - --device=dri
  - --env=SESSION_MANAGER= # required to avoid Qt warning
  - --filesystem=home

modules:
  - shared-modules/glew/glew.json

  - name: tomviz    
    buildsystem: simple
    build-commands:
         - mkdir tomvizsuperbuild
         - cd tomvizsuperbuild
         - pwd
         - cmake -DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo ../tomvizsuper
         - cmake --build .
    sources:
      - type: git
        url: https://github.com/OpenChemistry/tomvizsuper
        commit: 51f93b92edf9a65f858896a72a97aff184409b80
```

Tomviz dependency, Paraview required an out-of-source build.

```
ParaView requires an out-of-source build.  Please create a separate binary
directory and run CMake there.
```

So I attempt to create tomvizsuperbuild folder with `cd tomvizsuperbuild`
However, cd command does not seems to work.

`pwd` show that the working directory does not change.

The build log.

```
Running: mkdir tomvizsuperbuild
Running: cd tomvizsuperbuild
Running: pwd
/run/build/tomviz
Running: cmake -DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo ../tomvizsuper
CMake Error: The source directory "/run/build/tomvizsuper" does not exist.
```
How do I perform out-of-source build with flatpak-builder?

Thank you.
