### ISSUE TITLE
"builddir: true" does not support "buildsystem: simple"

### ISSUE THREAD

**Issue by kevinsmia1939** [flatpak/flatpak-builder#379]
Operating System: openSUSE Tumbleweed 20210227
KDE Plasma Version: 5.21.0
KDE Frameworks Version: 5.79.0
Qt Version: 5.15.2
Kernel Version: 5.10.16-1-default
OS Type: 64-bit
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-3770 CPU @ 3.40GHz
Memory: 7.5 GiB of RAM
Graphics Processor: Mesa DRI Intel® HD Graphics 4000

flatpak-builder 1.0.11
Flatpak 1.10.1

I was trying to build flatpak for Tomviz.

https://github.com/OpenChemistry/tomvizsuper

Tomviz required out of source build, which mean that I have to create a new folder and build in it. 
builddir: true solve this for me.
However, if I use "buildsystem: cmake", it will try to "install" which Tomviz does not have install target.
Causing this error  `make: *** No rule to make target 'install'.  Stop.`

So I resort to "buildsystem: simple" as shown below.
However, "builddir: true" does not seems to be in effect.
pwd command show that I did not move to separate build directory.

```
Running: pwd
/run/build/tomviz
Running: cmake -DTomvizSuper_INSTALL_PREFIX=/app
...
CMake Error at CMakeLists.txt:44 (message):
  ParaView requires an out-of-source build.  Please create a separate binary
  directory and run CMake there.
```

```
app-id: org.tomviz.Tomviz
runtime: org.kde.Platform
sdk: org.kde.Sdk
runtime-version: '5.15'
command: tomviz
finish-args:
  - --share=ipc
  - --socket=wayland
  - --socket=fallback-x11
  - --device=dri
  #- --filesystem=home

modules:
  - shared-modules/glew/glew.json
  
  - name: python3-numpy
    buildsystem: simple
    build-commands:
      - rm pyproject.toml
      - pip3 install --prefix=/app .
    sources:
      - type: archive
        url: https://files.pythonhosted.org/packages/51/60/3f0fe5b7675a461d96b9d6729beecd3532565743278a9c3fe6dd09697fa7/numpy-1.19.5.zip
        sha256: a76f502430dd98d7546e1ea2250a7360c065a5fdea52b2dffe8ae7180909b6f4  

  - name: tomviz
    buildsystem: simple
    builddir: true
    build-commands:
         - pwd
         - cmake -DTomvizSuper_INSTALL_PREFIX=/app
         - cmake --build .
    sources:
      - type: git
        url: https://github.com/OpenChemistry/tomvizsuper
        commit: 51f93b92edf9a65f858896a72a97aff184409b80
```

Any way to get around this?
Thank you.
