### ISSUE TITLE
Program inside an extension can't find glib compiled schema inside prefix

### ISSUE THREAD

**Issue by ranisalt** [flatpak/flatpak-builder#398]
## Linux distribution and version
Manjaro Linux 20210612-1

## Flatpak-builder version
1.0.12

## Flatpak version
1.11.1

## Description of the problem
I'm trying to build [yad](https://github.com/v1cont/yad) as a module inside an extension for [com.valvesoftware.Steam](https://github.com/flathub/com.valvesoftware.Steam). The `make install` step for yad runs `glib-compile-schemas` but reads and stores the definitions in `/app/utils/steamtinkerlaunch/share/glib-2.0/schemas/gschemas.compiled`, because `/app/utils/steamtinkerlaunch` set as `build-options.prefix`.

When running `flatpak run --command=yad com.valvesoftware.Steam` I get the following error:

```
(yad:2): GLib-GIO-ERROR **: 17:05:02.090: Settings schema 'yad.settings' is not installed
```

Now I don't know a lot about glib/gschema in general, but apparently it is looking in `XDG_DATA_DIRS` which is set to `XDG_DATA_DIRS=/app/share:/usr/share:/usr/share/runtime/share:/run/host/user-share:/run/host/share` in the sandbox, so `/app/utils/steamtinkerlaunch/share` should also be there. I found no way to append to `XDG_DATA_DIRS` in the documentation.

## Steps to reproduce
This is the yaml configuration:

```yml
---
id: com.valvesoftware.Steam.Utility.steamtinkerlaunch
branch: stable
runtime: com.valvesoftware.Steam
runtime-version: stable
sdk: org.freedesktop.Sdk//20.08
build-extension: true

build-options:
  prefix: /app/utils/steamtinkerlaunch
  prepend-path: /app/utils/steamtinkerlaunch/bin

cleanup:
  - /include
  - /man
  - /share/aclocal
  - /share/doc
  - /share/man

modules:
  - name: stl
    no-autogen: true
    sources:
      - type: archive
        url: https://github.com/frostworx/steamtinkerlaunch/archive/v6.8.tar.gz
        sha256: 45179feaeb67dd2f0a44fb03e4e7bbaac0e7ec67cdb9dc9a36d592786e56360e

    modules:
      - name: yad
        sources:
          - type: archive
            url: https://github.com/v1cont/yad/releases/download/v10.1/yad-10.1.tar.xz
            sha256: 742a5bd55de4b249eee6780bddeccb05c7ff4b158fd9743808f7d280219fd3ab

        modules:
          - shared-modules/intltool/intltool-0.51.json
```

It is required to clone [flathub/shared-modules
(https://github.com/flathub/shared-modules) in the same folder. I am building with `flatpak-builder --user --force-clean build com.valvesoftware.Steam.Utility.steamtinkerlaunch.yml --install`
