### ISSUE TITLE
fails to get git submodule

### ISSUE THREAD

**Issue by FuchtelJockel** [flatpak/flatpak-builder#402]
## Linux distribution and version
openSUSE Tumbleweed 20210708
## Flatpak-builder version
flatpak-builder 1.0.12
## Flatpak version
Flatpak 1.11.2
## Description of the problem
fails to download git submodule
```
[submodule "libqrencode"]
    path = libqrencode
    url = https://github.com/fukuchi/libqrencode.git
    ignore = dirty
```
```
Fetching git repo https://git.jami.net/savoirfairelinux/jami-client-qt.git, ref refs/heads/master
remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
Failed to download sources: module jami-qt: Not a gitlink tree: libqrencode
```
## Steps to reproduce
`flatpak-builder --user --install --force-clean --ccache ./build net.jami.Jami.yml`
```yml
app-id: net.jami.Jami
runtime: org.kde.Platform
runtime-version: '5.15'
sdk: org.kde.Sdk
command: jami-qt

finish-args:
  - --share=ipc
  - --socket=fallback-x11
  - --socket=wayland
  - --socket=pulseaudio
  - --share=network

modules:
  - name: jami-qt
    buildsystem: cmake
    builddir: true
    sources:
      - type: git
        url: https://git.jami.net/savoirfairelinux/jami-client-qt.git
        commit: 285316dd3273df5fbcf0c5bd536beedd4c1c510f
```
