### ISSUE TITLE
Segfaults on trying to load recursive external manifest file reference

### ISSUE THREAD

**Issue by gasinvein** [flatpak/flatpak-builder#412]
## Linux distribution and version

Fedora 34

## Flatpak-builder version

1.1.1

## Flatpak version

1.11.2

## Description of the problem

Manifest can include other manifests from external files. If such manifest includes itself, flatpak-builder tries to load it, and segfaults.
I believe recursive manifest reference should be explicitly prohibited.

## Steps to reproduce

- Create a dummy module manifest file `recursive-module.yml` with this contents
  ```yaml
     name: recursive-module
     buildsystem: simple
     build-commands: []
     modules:
       - recursive-module.yml
  ```
- Add a reference to this file to an app manifest `modules`
- Try to build the app
