### ISSUE TITLE
[Bug]: Fails to pull git repo with submodules

### ISSUE THREAD

**Issue by zocker-160** [flatpak/flatpak-builder#466]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak-builder/issues) for a bug that matches the one I want to file, without success.

### flatpak-builder version

1.2.2

### Flatpak version

1.12.4

### How to reproduce

- create `test.yml` (see below)
- try to build it

### Expected Behavior

It should pull everything just like it would with `git clone --recurse-submodules https://github.com/dail8859/NotepadNext.git`

### Actual Behavior

`test.yml`
```yml
app-id: test
runtime: org.kde.Platform
runtime-version: "5.15-21.08"
sdk: org.kde.Sdk
    
modules:
    - name: NotepadNext
      buildsystem: simple
      build-commands:
        - echo "just a test"
      sources:
        - type: git
          url: https://github.com/dail8859/NotepadNext.git
          tag: v0.4.9

```
```
$ flatpak-builder --force-clean build/ test.yml 
Downloading sources
Fetching git repo https://github.com/dail8859/NotepadNext.git, ref refs/tags/v0.4.9
remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
Fetching full git repo https://github.com/itay-grudev/SingleApplication.git
Fetching git repo https://gitlab.freedesktop.org/uchardet/uchardet.git, ref refs/tags/v0.0.7
remote: Enumerating objects: 1, done.
remote: Counting objects: 100% (1/1), done.
remote: Total 1 (delta 0), reused 1 (delta 0), pack-reused 0
Unpacking objects: 100% (1/1), 828 bytes | 828.00 KiB/s, done.
Fetching full git repo https://github.com/editorconfig/editorconfig-core-qt.git
Initialized empty Git repository in /home/bene/Programmierkram/Linux_Packaging/Flatpak/NotepadNext/.flatpak-builder/git/git_github.com_editorconfig_editorconfig-core-test.git-F0ZBK1/
fatal: remote error: 
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
Failed to download sources: module NotepadNext: Der Kindprozess wurde mit Status 128 beendet
```
