### ISSUE TITLE
[Feature request]: Override request headers for archive/file downloads

### ISSUE THREAD

**Issue by ranisalt** [flatpak/flatpak-builder#513]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak-builder/issues) for a feature request that matches the one I want to file, without success.

### Suggestion

I am building a package that depends on a file that is downloaded from the package's website. The download is available to the public, however, it requires that the `Referer` HTTP header set to a specific value (the page where the download button is). An example would be:

```yml
    sources:
      - type: archive
        url: https://static.example.com/download/example.x64.tar.gz
        referer: https://example.com/download.php
        sha256: ...
```

It seems that Flatpak uses curl for downloading files, guessing from the recognizable progress output. In curl, I just need to provide `-e https://example.com/download.php` and it downloads fine.
