### ISSUE TITLE
[Bug]: flatpak-builder hangs when module is named git

### ISSUE THREAD

**Issue by JakobDev** [flatpak/flatpak-builder#518]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak-builder/issues) for a bug that matches the one I want to file, without success.

### flatpak-builder version

1.2.3

### Flatpak version

1.15.1

### How to reproduce

Try to build this manifest:
```yaml
app-id: org.example.App
runtime: org.freedesktop.Platform
runtime-version: '22.08'
sdk: org.freedesktop.Sdk

modules:
  - name: git
    buildsystem: autotools
    sources:
      - type: archive
        url: https://mirrors.edge.kernel.org/pub/software/scm/git/git-2.39.1.tar.xz
        sha256: 40a38a0847b30c371b35873b3afcf123885dd41ea3ecbbf510efa97f3ce5c161
```

### Expected Behavior

The manifest should build

### Actual Behavior

The Build hangs in a endless loop while printing
```
(flatpak-builder:916): flatpak-builder-WARNING **: 10:41:13.825: Running debugedit failed: Der Kindprozess wurde mit Status 1 beendet
compressing debuginfo in: /home/jakob/Flatpak/test/.flatpak-builder/rofiles/rofiles-5QGhHN/files/libexec/git-core/git-update-server-info
processing: /home/jakob/Flatpak/test/.flatpak-builder/rofiles/rofiles-5QGhHN/files/libexec/git-core/git-update-server-info
[30] .debug_aranges compressed -> .zdebug_aranges (18384 => 4041 21.98%)
[31] .debug_info compressed -> .zdebug_info (7915465 => 4169940 52.68%)
[32] .debug_abbrev compressed -> .zdebug_abbrev (561094 => 113772 20.28%)
[33] .debug_line compressed -> .zdebug_line (2100573 => 1004771 47.83%)
[34] .debug_str compressed -> .zdebug_str (315491 => 111380 35.30%)
[35] .debug_line_str compressed -> .zdebug_line_str (9384 => 3207 34.18%)
[36] .debug_loclists compressed -> .zdebug_loclists (2746563 => 1222574 44.51%)
[37] .debug_rnglists compressed -> .zdebug_rnglists (338568 => 229537 67.80%)
[40] Updating section string table
stripping /home/jakob/Flatpak/test/.flatpak-builder/rofiles/rofiles-5QGhHN/files/libexec/git-core/git-update-server-info to /home/jakob/Flatpak/test/.flatpak-builder/rofiles/rofiles-5QGhHN/files/lib/debug/libexec/git-core/git-update-server-info.debug
/usr/lib/flatpak-builder-debugedit: Failed to chmod input file '/home/jakob/Flatpak/test/.flatpak-builder/rofiles/rofiles-5QGhHN/files/libexec/git-core/git-version' to make sure we can read and write: Read-only file system
/usr/lib/flatpak-builder-debugedit: Failed to open input file '/home/jakob/Flatpak/test/.flatpak-builder/rofiles/rofiles-5QGhHN/files/libexec/git-core/git-version': Read-only file system
```

**Comment by TingPing** [comment]
It has nothing to do with the name of the module, the installed `git` is just causing issues.

**Comment by TingPing** [comment]
```yaml
  - name: git2
    buildsystem: autotools
    make-install-args:
      - NO_INSTALL_HARDLINKS=1
    sources:
      - type: archive
        url: https://mirrors.edge.kernel.org/pub/software/scm/git/git-2.39.1.tar.xz
        sha256: 40a38a0847b30c371b35873b3afcf123885dd41ea3ecbbf510efa97f3ce5c161
```
