### ISSUE TITLE
Zip extraction is not quiet

### ISSUE THREAD

**Issue by Mailaender** [flatpak/flatpak-builder#524]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak-builder/issues) for a bug that matches the one I want to file, without success.

### flatpak-builder version

1.2.3

### Flatpak version

1.15.3

### How to reproduce

```yaml
    sources:
      - type: archive
        url: https://downloads.sourceforge.net/project/src.zip
```

### Expected Behavior

`unzip -q`

### Actual Behavior

will spam the console with
>   inflating: folder/file.java

so you can't see what happened before.
