### ISSUE TITLE
--build-shell not available when running org.flatpak.Builder as a Flatpak app

### ISSUE THREAD

**Issue by 2-www** [flatpak/flatpak-builder#550]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak-builder/issues) for a bug that matches the one I want to file, without success.

### flatpak-builder version

1.3.1

### Flatpak version

1.14.4

### How to reproduce

manifest.yaml:
```yaml
app-id: org.example.App
runtime: org.freedesktop.Platform
runtime-version: "22.08"
sdk: org.freedesktop.Sdk
modules:
- name: example
  no-autogen: true
  buildsystem: simple
  build-commands: []
```

commands:
```
flatpak run org.flatpak.Builder --force-clean build-dir manifest.yaml
flatpak run org.flatpak.Builder --build-shell=example build-dir manifest.yaml
```

### Expected Behavior

it opens a shell

### Actual Behavior

```
bwrap: No permissions to creating new namespace, likely because the kernel does not allow non-privileged user namespaces. On e.g. debian this can be enabled with 'sysctl kernel.unprivileged_userns_clone=1'.
```

### Additional Information

the kernel allows unprivileged userns:

```
$ /sbin/sysctl kernel.unprivileged_userns_clone
kernel.unprivileged_userns_clone = 1
```
