### ISSUE TITLE
Can't find autogen, autogen.sh or bootstrap

### ISSUE THREAD

**Issue by stsp** [flatpak/flatpak-builder#611]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak-builder/issues) for a bug that matches the one I want to file, without success.

### flatpak-builder version

1.4.1

### Flatpak version

1.15.8

### How to reproduce

Add some autotools-based module
without autogen.sh, for example:
```
  - name: jansson
    buildsystem: autotools
    sources:
      - type: git
        url: https://github.com/akheron/jansson.git
        branch: master
```

### Expected Behavior

`autoreconf` should be run.

### Actual Behavior

`Error: module jansson: Can't find autogen, autogen.sh or bootstrap`

### Additional Information

If there is no `configure` and `autogen.sh`
but `configure.ac` exist, just run `autoreconf`.
