### ISSUE TITLE
Can't find autogen, autogen.sh or bootstrap

### ISSUE THREAD

**Issue by stsp** [flatpak/flatpak-builder#612]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak-builder/issues) for a bug that matches the one I want to file, without success.

### flatpak-builder version

1.4.1

### Flatpak version

1.15.8

### How to reproduce

Add some module w/o `autogen.sh`, for example:
```
  - name: jansson
    buildsystem: autotools
    sources:
      - type: git
        url: https://github.com/akheron/jansson.git
        branch: master
```

### Expected Behavior

`autoreconf` and successful build.

### Actual Behavior

`Error: module jansson: Can't find autogen, autogen.sh or bootstrap`

### Additional Information

`autoreconf` should be used when no
`configure` or `autogen.sh` found, but
`configure.ac` is there.

**Comment by TingPing** [comment]
`autoreconf` isn't necessarily the right answer, so f-b doesn't try to guess.

You can easily make your own autogen.sh this with:

```yaml
  - name: jansson
    sources:
      - type: git
        url: https://github.com/akheron/jansson.git
        branch: master
      - type: script
        commands: ['autoreconf']
```

**Comment by stsp** [comment]
That worked!
Thank you.
Do you happen to know the same magic
for meson btw? I need to pass `--native-file`
and `--cross-file` to `meson setup` and I
don't know how.
Is this all documented?
The main flatpak doc leaves many questions,
but maybe I just missed these parts...

**Comment by TingPing** [comment]
> I need to pass --native-file and --cross-file to meson setup and I don't know how.

You can set `config-opts` for the module, but this sounds odd to me. You should not cross-compile in flatpak generally.

**Comment by stsp** [comment]
I don't know how to tell meson to
use `clang` as a compiler, other than
by adding it into a toolchain file, and
then using `--native-file`.
As for the `--cross-file` - I need that one
too, as I am building an emulator of
another arch.

Thanks for the help!
I am not sure if anything you say, is
actually documented somewhere, but
maybe it is. :)

**Comment by TingPing** [comment]
```yaml
build-options:
  env:
   CC: clang
   CXX: clang++
```
