### ISSUE TITLE
/sbin/chown: Invalid argument when building sudo

### ISSUE THREAD

**Issue by stsp** [flatpak/flatpak-builder#613]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak-builder/issues) for a bug that matches the one I want to file, without success.

### flatpak-builder version

1.4.1

### Flatpak version

1.15.8

### How to reproduce

```
  - name: sudo
    buildsystem: autotools
    sources:
      - type: git
        url: https://github.com/sudo-project/sudo.git
        branch: main
```

### Expected Behavior

Build and installs.

### Actual Behavior

Multiple errors like
`/sbin/chown: changing ownership of '/app/libexec/sudo/libsudo_util.so.0.0.0': Invalid argument`
when installing.

### Additional Information

sudo explicitly specifies group and ownership
to `install` when installing. That leads to explicit
chmods, even though the files are root-owned
anyway.
I am not sure why that fails with "Invalid argument".
I suppose flatpak uses some FS that doesn't
support chown?
