### ISSUE TITLE
Flatpak-builder --install only installs the Sdk and not the Platform when using combined runtime manifest

### ISSUE THREAD

**Issue by dcbaker** [flatpak/flatpak-builder#630]
### Checklist

- [x] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak-builder/issues) for a bug that matches the one I want to file, without success.

### flatpak-builder version

1.4.4

### Flatpak version

1.14.4

### How to reproduce

1. Build a platform and SDK together:
    ```yaml
    build-runtime: true
    id: com.example.Sdk
    id-platform: com.example.Platform
    runtime-version: "24.08"
    runtime: org.freedesktop.Platform
    sdk: org.freedesktop.Sdk
    ```
2. flatpak-builder build com.example.sdk.yml --install --user

### Expected Behavior

Both the Platform and Sdk would be installed

### Actual Behavior

Only the Sdk is installed
