### ISSUE TITLE
Help: flatpak-builder build tips

### ISSUE THREAD

**Issue by q962** [flatpak/flatpak-builder#638]
I have a problem.

The project needs to download binary files when building.

The files are stored in the project path.

Now the problem is that when I repeat the build, the files will be downloaded repeatedly.

So I have to use dir or file to copy the files.

Then my yml file becomes impure.

The yml file now is just my own.

I also need to copy the project code.

So I should prepare two yml files. One is for local use.

The other is a normal yml file. There is only one source named git type

Is there a way to solve this problem, such as using module overlay?

Although it is still two files, at least large sections of duplicate content are avoided.

-----

```
    sources:
      - type: archive
        path: archive.tar
        strip-components: 0
      - type: dir
        path: ../build/linux/x86_64/
        dest: build/linux/x86_64/
```

My project also has submodules, I need to use a special command to package my project files
