### ISSUE TITLE
Flatpak-builder cannot find dependency even with --install-deps-from

### ISSUE THREAD

**Issue by RalfJung** [flatpak/flatpak-builder#640]
### Checklist

- [x] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak-builder/issues) for a bug that matches the one I want to file, without success.

### flatpak-builder version

flatpak-builder-1.4.4

### Flatpak version

Flatpak 1.16.0

### How to reproduce

I have the following in my manifest:

```
sdk: org.freedesktop.Sdk
runtime: org.freedesktop.Sdk
runtime-version: '24.08'
base: org.electronjs.Electron2.BaseApp
base-version: '24.08'
```

 (I have absolutely no clue if the version numbers make any sense as I wasn't able to find good docs on what to put here; this is copy-pasted from https://github.com/flathub/com.vscodium.codium/blob/master/com.vscodium.codium.yaml.)

<details><summary>Full manifest</summary>

```
app-id: io.keybase.Keybase

sdk: org.freedesktop.Sdk
runtime: org.freedesktop.Sdk
runtime-version: '24.08'
base: org.electronjs.Electron2.BaseApp
base-version: '24.08'

command: keybase

separate-locales: false
rename-desktop-file: keybase.desktop
rename-icon: keybase

finish-args:
  # X11 performance
  - --share=ipc
  # We need X11
  - --socket=x11
  # Access to wayland
  - --socket=wayland
  # Network Access
  - --share=network
  # Access for downloading files
  - --filesystem=xdg-download
  # We need to send notifications
  - --talk-name=org.freedesktop.Notifications
  - --talk-name=org.kde.StatusNotifierWatcher
  # Allow running in background
  - --talk-name=org.freedesktop.portal.Background

modules:
  - name: keybase
    buildsystem: simple
    build-commands:
      - install -Dm0755 keybase.sh "${FLATPAK_DEST}/bin/keybase"
      - |
        bsdtar -Oxf keybase.deb 'data.tar.xz' |
          bsdtar -xf -
      - mv opt/keybase "${FLATPAK_DEST}"/
      - mv usr/bin "${FLATPAK_DEST}"/keybase/
      # Desktop file and icon
      - install -Dm0644 "usr/share/applications/keybase.desktop" "${FLATPAK_DEST}/share/applications/keybase.desktop"
      - desktop-file-edit --set-key=Exec --set-value='keybase %U' "${FLATPAK_DEST}/share/applications/keybase.desktop"
      - |
        for size in 16 32 128 256 512; do
          install -Dm0644 "usr/share/icons/hicolor/${size}x${size}/apps/keybase.png" "${FLATPAK_DEST}/share/icons/hicolor/${size}x${size}/apps/keybase.png"
        done
      - desktop-file-edit --set-key=Icon --set-value="keybase" "${FLATPAK_DEST}/share/applications/keybase.desktop"
    sources:
      - type: file
        dest-filename: keybase.deb
        # Filename found in https://prerelease.keybase.io/deb/dists/stable/main/binary-amd64/Packages.
        url: https://s3.amazonaws.com/prerelease.keybase.io/linux_binaries/deb/keybase_6.4.0-20240821175720.3212f60cc5_amd64.deb
        sha256: 386b9c90c5170f37c720c8506a060964e6d5e16e8bb9fa9378888283e7393233
      - type: file
        path: keybase.sh
```

</details>

Note sure if the rest of the repo is also needed to reproduce the problem, you can find it at https://github.com/RalfJung/io.keybase.Keybase.

Now I run
```
flatpak-builder --user --install --install-deps-from=flathub --force-clean builddir io.keybase.Keybase.yml
```

### Expected Behavior

This should fetch the dependencies that are missing and then successfully build the flatpak.

### Actual Behavior

I get an error:
```
Dependency Sdk: org.freedesktop.Sdk 24.08
Installing org.freedesktop.Sdk/x86_64/24.08 from flathub
error: No remote refs found for ‘flathub’
Error installing deps: running `flatpak --user install -y --noninteractive flathub org.freedesktop.Sdk/x86_64/24.08`: Child process exited with code 1
```
I don't know what this is trying to tell me. With a brief search I was unable to find guidance on which versions to put here (the official docs at https://docs.flatpak.org/en/latest/manifests.html use an example involving Gnome which would not be right for my flatpak). Surely if the vscodium package uses these versions then they actually do exist?
